// Shared geographic lookup tables for map layers.
// All coordinates are [lng, lat] (Leaflet uses lat/lng but canvas helpers use lng first).

export const REGION_COORDS: Record<string, [number, number]> = {
  'Taiwan Strait':    [121.0, 23.5],
  'Eastern Europe':  [31.0,  50.5],
  'Persian Gulf':    [51.5,  26.5],
  'Korean Peninsula':[127.5, 38.5],
  'Gaza & Lebanon':  [35.5,  32.5],
  'South China Sea': [113.0, 12.0],
  'Arctic':          [15.0,  78.0],
  'Global':          [0.0,   20.0],
  'Middle East':     [45.0,  30.0],
  'Europe':          [15.0,  50.0],
  'Asia-Pacific':    [135.0, 25.0],
  'Asia':            [90.0,  35.0],
  'Pacific':         [170.0, 15.0],
};

export const LEADER_COORDS: Record<string, [number, number]> = {
  usa:         [-98,   38],
  china:       [104,   35],
  russia:      [90,    60],
  iran:        [54,    32],
  israel:      [35,    31.5],
  uk:          [-1,    52],
  france:      [2,     46],
  germany:     [10,    51],
  turkey:      [35,    39],
  saudiarabia: [45,    24],
  india:       [78,    20],
  pakistan:    [70,    30],
  japan:       [138,   36],
  southkorea:  [128,   36],
  northkorea:  [127,   40],
  ukraine:     [31,    49],
  taiwan:      [121,   23.5],
  nato:        [15,    50],
  europe:      [15,    50],
  un:          [0,     20],
  imf:         [-77,   38.9],
};

export const LEADER_NAMES: Record<string, string> = {
  usa:         'USA',
  china:       'CHINA',
  russia:      'RUSSIA',
  iran:        'IRAN',
  israel:      'ISRAEL',
  uk:          'UK',
  france:      'FRANCE',
  germany:     'GERMANY',
  turkey:      'TÜRKIYE',
  saudiarabia: 'SAUDI ARABIA',
  india:       'INDIA',
  pakistan:    'PAKISTAN',
  japan:       'JAPAN',
  southkorea:  'S.KOREA',
  northkorea:  'N.KOREA',
  ukraine:     'UKRAINE',
  taiwan:      'TAIWAN',
  nato:        'NATO',
};

export const LEADER_FLAGS: Record<string, string> = {
  usa:         '🇺🇸',
  china:       '🇨🇳',
  russia:      '🇷🇺',
  iran:        '🇮🇷',
  israel:      '🇮🇱',
  uk:          '🇬🇧',
  france:      '🇫🇷',
  germany:     '🇩🇪',
  turkey:      '🇹🇷',
  saudiarabia: '🇸🇦',
  india:       '🇮🇳',
  pakistan:    '🇵🇰',
  japan:       '🇯🇵',
  southkorea:  '🇰🇷',
  northkorea:  '🇰🇵',
  ukraine:     '🇺🇦',
  taiwan:      '🇹🇼',
  nato:        '🏛',
};
